Models/Requests.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ImcLabApp.Models
{
    public class Requests
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string medicalNumber { get; set; }
        [Required]
        public string nationalId { get; set; }
        [Required]
        public string dateTime { get; set; }

        public bool lb_Request { get; set; }
        public bool rd_Request { get; set; }
        public bool tr_Request { get; set; }

    }
}

Models/Tumors.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ImcLabApp.Models
{
    public class Tumors
    {
        public int Id { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage ="من فضلك أدخل أسم التقرير")]
        public string testName { get; set; }

        [Required]
        public string Name { get; set; }
        [Required]
        public string urlName { get; set; }
        [Required]
        public string Datetime { get; set; }

        [Required]
        [ForeignKey("Patients")]
        public int patients_Id { get; set; }
        public virtual Patients Patients { get; set; }
    }
}

Controllers/Api/RequestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using ImcLabApp.Models;
namespace ImcLabApp.Controllers.Api
{
    public class RequestsController : ApiController
    {
        AppDbContext db = new AppDbContext();

        [HttpGet]
        public IEnumerable<Requests>  Requests()
        {
            var requests = db.Requests.ToList();
            return requests;
        }
        
        [HttpPost]
        public Requests Requests(Requests requests)
        {
            if (requests == null)
                throw new HttpResponseException(HttpStatusCode.BadRequest);

            db.Requests.Add(requests);
            db.SaveChanges();
            return(requests);
        }
    }
}

Controllers/TumorsController.cs
using ImcLabApp.Models;
using ImcLabApp.Models.BackUpSystemModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ImcLabApp.Controllers
{
    public class TumorsController : Controller
    {
        AppDbContext db = new AppDbContext();
        // GET: Radios
        public ActionResult Index()
        {
            return View();
        }//--------------------------------------//
        //CRUD OPERATIONS USING ASP.NET MVC AND DATATABLE OF PATIENTS.
        //-------------------------------------//

        // GET ALL PATIENTS.
        public JsonResult GetPatients()
        {
            db.Configuration.ProxyCreationEnabled = false;
            return Json(new { data = db.Patients.ToList() }, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public ActionResult AddOrEdit(int id = 0)
        {
            if (id == 0)
            {
                return View(new Patients());
            }
            else
            {
                return View(db.Patients.Where(p => p.Id.Equals(id)).FirstOrDefault<Patients>());
            }
        }
        [HttpPost]
        public ActionResult AddOrEdit(int id, Patients p)
        {

            if (p.Id == 0)
            {
                var patientInDB = db.Patients.Where(m => m.medicalNumber == p.medicalNumber).FirstOrDefault();
                if (patientInDB == null)
                {
                    db.Patients.Add(p);
                    db.SaveChanges();
                    return Json(new { success = true, message = "تم الإضافة" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = true, message = "هذ المريض موجود بالفعل" }, JsonRequestBehavior.AllowGet);
                }

            }
            else
            {
                var patientInDB = db.Patients.Where(m => m.medicalNumber == p.medicalNumber).FirstOrDefault();
                if (patientInDB == null)
                {
                    db.Entry(p).State = EntityState.Modified;
                    db.SaveChanges();
                    return Json(new { success = true, message = "تم التعديل" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = true, message = "هذ المريض موجود بالفعل" }, JsonRequestBehavior.AllowGet);
                }

            }

        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var patient = db.Patients.Where(p => p.Id.Equals(id)).FirstOrDefault<Patients>();
            db.Patients.Remove(patient);
            db.SaveChanges();
            return Json(new { success = true, message = "تم المسح" }, JsonRequestBehavior.AllowGet);
        }

        //-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
        //----------------------------------------Patient Profile-------------------------------------------
        //-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

        // GET: patientsProfile
        public ActionResult patientProfile(int? id)
        {
            var patients = db.Patients.Where(e => e.Id == id).FirstOrDefault();

            ViewBag.error = TempData["error"];
            ViewBag.success = TempData["success"];
            ViewBag.patientId = patients.Id;
            return View();
        }

        public JsonResult getPatientById(int id)
        {
            db.Configuration.ProxyCreationEnabled = false;
            var patient = db.Patients.Where(p => p.Id.Equals(id)).FirstOrDefault<Patients>();
            return Json(patient, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetPatientResult(int? id)
        {
            db.Configuration.ProxyCreationEnabled = false;
            var results = db.Tumors.Where(l => l.patients_Id == id).ToList();
            return Json(results, JsonRequestBehavior.AllowGet);
        }

        //-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
        //Complete Base File Controllers.
        //-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
        public ActionResult uploadFile(HttpPostedFileBase upFile, int id, Tumors tumor)
        {
            if (upFile != null && tumor.testName != null)
            {
                if (upFile.ContentType == "application/pdf")
                {
                    Tumors tumors = new Tumors();
                    tumors.patients_Id = id;

                    var info = TimeZoneInfo.FindSystemTimeZoneById("Egypt Standard Time");
                    DateTimeOffset localServerTime = DateTimeOffset.Now;
                    DateTimeOffset localTime = TimeZoneInfo.ConvertTime(localServerTime, info);

                    var dateTime = localTime.ToString("dd/MM/yyyy hh:mm tt");

                    string UniquefileName = Guid.NewGuid() + Path.GetFileName(upFile.FileName);
                    string filePath = Server.MapPath("~/Uploaded/");
                    string actualPath = Path.Combine(filePath + UniquefileName);
                    upFile.SaveAs(actualPath);
                    tumors.Name = UniquefileName;
                    tumors.urlName = actualPath;
                    tumors.testName = tumor.testName;
                    tumors.Datetime = dateTime;

                    db.Tumors.Add(tumors);
                    db.SaveChanges();
                    ViewData["uploadSuccessMessage"] = "تم الرفع بنجاح";
                    TempData["success"] = ViewData["uploadSuccessMessage"];
                    return RedirectToAction("patientProfile/" + id);
                }
                else
                {
                    ViewData["errorTypeMessage"] = "هذا الملف ليس pdf";
                    TempData["error"] = ViewData["errorTypeMessage"];
                    return RedirectToAction("patientProfile/" + id);
                }

            }
            else
            {
                ViewData["uploadErrorMessage"] = "من فضلك إختر الملف أو ادخل أسم التحليل";
                TempData["error"] = ViewData["uploadErrorMessage"];
                return RedirectToAction("patientProfile/" + id);

            }
        }
        public FileResult Reader(string FileName)
        {
            string filePath = Server.MapPath("~/Uploaded/");

            string actualPath = Path.Combine(filePath + FileName);

            var fileStream = new FileStream(actualPath, FileMode.Open, FileAccess.Read);

            var fsResult = new FileStreamResult(fileStream, "application/pdf");

            return fsResult;
        }
        public ActionResult Downloader(string FileName)
        {
            string filePath = Server.MapPath("~/Uploaded/");

            string fullPath = Path.Combine(filePath + FileName);

            byte[] fileBytes = System.IO.File.ReadAllBytes(fullPath);

            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, FileName);

        }
        public ActionResult Deleter( int fileId, string FileName)
        {

            var fileInDb = db.Tumors.Where(t => t.Id == fileId).FirstOrDefault();
            var fileInBackUpTests = db.tb_TumorsBackUps.Where(b => b.Name == FileName).FirstOrDefault();
            string filePath = Server.MapPath("~/Uploaded/");
            string fullPath = Path.Combine(filePath + FileName);

            //----------------------------------------------------------------------------
            var info = TimeZoneInfo.FindSystemTimeZoneById("Egypt Standard Time");
            DateTimeOffset localServerTime = DateTimeOffset.Now;
            DateTimeOffset localTime = TimeZoneInfo.ConvertTime(localServerTime, info);
            //----------------------------------------------------------------------------

            if (System.IO.File.Exists(fullPath))
            {
                if (fileInBackUpTests != null)
                {
                    db.Tumors.Remove(fileInDb);
                    db.SaveChanges();
                    return Json("هذا الملف غير متاح", JsonRequestBehavior.AllowGet);
                }
                else
                {
                     tb_TumorsBackUp tb_TumorsBackUp = new tb_TumorsBackUp();

                    var TestName = fileInDb.testName;
                    var fileName = fileInDb.Name;
                    var fileUrl = fileInDb.urlName;
                    var AddedDate = fileInDb.Datetime;
                    var patientId = fileInDb.patients_Id;

                    //get patient from database.
                    var patients = db.Patients.Where(p => p.Id == patientId).FirstOrDefault();
                    var patientName = patients.userName;
                    var patientMedicalNumber = patients.medicalNumber;
                    var userName = Session["uName"].ToString();

                    //copying data from tests table to backup table.
                    tb_TumorsBackUp.testName = TestName;
                    tb_TumorsBackUp.Name = fileName;
                    tb_TumorsBackUp.urlName = fileUrl;
                    tb_TumorsBackUp.dateWasAdded = AddedDate;
                    tb_TumorsBackUp.PatientName = patientName;
                    tb_TumorsBackUp.PatientMedicalNumber = patientMedicalNumber;
                    tb_TumorsBackUp.UserName = userName;
                    tb_TumorsBackUp.Datetime = localTime.ToString("dd/MM/yyyy hh:mm tt");
                    tb_TumorsBackUp.patients_Id = patientId;

                    db.tb_TumorsBackUps.Add(tb_TumorsBackUp);
                    db.Tumors.Remove(fileInDb);
                    db.SaveChanges();
                }

            }
            else
            {
                return Json("هذا الملف غير متاح", JsonRequestBehavior.AllowGet);
            }

            return Json("تم الحذف بنجاح", JsonRequestBehavior.AllowGet);

        }

Views/Tumors/AddOrEdit.cshtml
@model ImcLabApp.Models.Patients

@{
    if (@Session["uId"] == null)
    {
        Response.Redirect("/Login/login");
    }
    Layout = null;
}

<section dir="rtl">
    @using (Html.BeginForm("AddOrEdit", "Tumors", FormMethod.Post, new { onsubmit = "return SubmitForm(this)" }))
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.HiddenFor(model => model.Id)
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-12">
                @Html.LabelFor(model => model.medicalNumber)
            </div>
            <div class="col-md-12">
                @Html.EditorFor(model => model.medicalNumber, new { htmlAttributes = new { @class = "form-control", @type = "number", placeholder = "أدخل الرقم الطبي " } })
                @Html.ValidationMessageFor(model => model.medicalNumber, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12">
                @Html.LabelFor(model => model.NationalID)
            </div>
            <div class="col-md-12">
                @Html.EditorFor(model => model.NationalID, new { htmlAttributes = new { @class = "form-control", @type = "number", placeholder = "أدخل الرقم القومي / الباسبور " } })
                @Html.ValidationMessageFor(model => model.NationalID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12">
                @Html.LabelFor(model => model.userName)
            </div>
            <div class="col-md-12">
                @Html.EditorFor(model => model.userName, new { htmlAttributes = new { @class = "form-control", placeholder = "أدخل إسم المريض" } })
                @Html.ValidationMessageFor(model => model.userName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12">
                @Html.LabelFor(model => model.phoneNumber)
            </div>
            <div class="col-md-12">
                @Html.EditorFor(model => model.phoneNumber, new { htmlAttributes = new { @class = "form-control", @type = "number", maxlength = 11, placeholder = "أدخل رقم التليفون" } })
                @Html.ValidationMessageFor(model => model.phoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-12">
                <input type="submit" value="إضافة" class="btn btn-success" />
                <input type="reset" value="إعادة" class="btn btn-light" />
            </div>
        </div>
    </div>
    }
</section>

Views/Tumors/Index.cshtml
@{
    if (@Session["uId"] == null)
    {
        Response.Redirect("/Login/login");
    }
    ViewBag.BaseTitle = "الأورام";
    ViewBag.Title = "الصفحة الرئيسية";
    Layout = "~/Views/Shared/_Tur.cshtml";
}

@section Styles{
    

    <style>

        div.dataTables_wrapper div.dataTables_filter input {
            margin-left: 0.5em;
            display: inline-block;
            width: 100%;
            margin-right: 10px;
        }

        .ui-dialog .ui-dialog-titlebar {
            margin-bottom: 20px;
        }

        .ui-button-icon-space::after {
            display: none;
        }

        section .patientTableData {
            padding-bottom: 30px;
            z-index: -1000;
        }

        .dataTables_length {
            display: none;
        }

        #patientsTable_info {
            padding-top: 0px !important;
        }
    </style>

}
<section class="patientTableData" dir="rtl">
    <a class="btn btn-success" style="margin-bottom:20px; color:#fff;" onclick="PopupForm('@Url.Action("AddOrEdit","Tumors")')"><i class="icons-btn ion-plus-round"></i> إضافة مريض جديد</a>
    <table id="patientsTable" class="table table-bordered" width="100%">
        <thead>
            <tr>
                <th>الرقم الطبي</th>
                <th>الرقم القومي - الباسبور</th>
                <th>الإسم</th>
                <th>رقم الهاتف</th>
                <th> </th>
            </tr>
        </thead>
    </table>
</section>


@section Scripts{
    
    <script>
        var Popup, dateTable;
        $(document).ready(function () {
            dateTable = $('#patientsTable').DataTable({
                responsive: true,
                "ajax": {
                    "url": "/Labs/GetPatients",
                    "type": "GET",
                    "datatype": "JSON",
                },
                "columns": [
                    { "data": "medicalNumber" },
                    { "data": "NationalID" },
                    { "data": "userName" },
                    { "data": "phoneNumber" },
                    {
                        "data": "Id", "render": function (res) {
                            return "<a style='margin-left:5px; color:#fff;' class='btn btn-warning btn-sm' onclick = PopupForm('@Url.Action("AddOrEdit","Tumors")/" + res + "')><i class='icons-btn ion-edit'></i>تعديل</a><a class='btn btn-primary btn-sm' onclick = Profile(" + res + ") style=color:#fff;'><i class='icons-btn ion-upload' aria-hidden='true'></i>رفع </a>"
                        },
                        "orderable": false,
                        "searchable": false,
                        "width": "220px"
                    }
                ],
                "language": {
                    "emptyTable": "هذا الجدول لا يحتوى على أي مرضى, من فضل إضغط على *إضافة مريض جديد* ",
                    "search": " البحث : ",
                    "searchPlaceholder": "ابحث عن مريض",
                    "paginate": { "previous": "الصحفة السابقة", "next": "الصفحة التالية", },
                    "info": "إظهار _START_ إلى _END_ من _TOTAL_ مرضى",
                    "zeroRecords": "هذ البحث غير متطابق ",
                    "infoEmpty": "إظهار 0 إلى 0 من 0 مرضى",
                    "infoFiltered": "",
                    "lengthMenu": " إظهار  _MENU_"
                },
                "autoWidth": true
            });
        });


        function PopupForm(url) {
            var formDiv = $("<div/>");
            $.get(url)
                .done(function (res) {
                    formDiv.html(res);

                    Popup = formDiv.dialog({
                        autoOpen: true,
                        resizable: false,
                        title: "أضف مريض جديد",
                        width: 500,
                        height: 620,
                        close: function () {
                            Popup.dialog('destroy').remove()
                        }
                    });
                })
        }


        function SubmitForm(form) {
            $.validator.unobtrusive.parse(form);

            if ($(form).valid()) {

                $.ajax({
                    type: "POST",
                    url: form.action,
                    data: $(form).serialize(),
                    success: function (res) {
                        if (res.success) {
                            Popup.dialog("close");
                            dateTable.ajax.reload();

                            $.notify(res.message, {
                                globalPosition: "top center",
                                className: "success"
                            });
                        }
                    }
                });

            }
            return false;
        }

        function Profile(P_Id) {
            var url = '@Url.Action("patientProfile", "Tumors")/' + P_Id ;
            window.location.href = url;

            }
    </script>

}

Views/Tumors/Requests.cshtml
@{
    ViewBag.Title = "الطلبات";
    ViewBag.BaseTitle = "المعامل";
    Layout = "~/Views/Shared/_Tur.cshtml";
}

<div class="jumbotron p-2 pb-0">
    <div class="container">
        <h1>الطلبات</h1>
        <p class="lead">
            <i class="ion-alert-circled text-warning"></i> هذه الطلبات مرسلة من المريض في حالة الضغط على زر "تم" سيتم مسح الطلب لديك ويحفظ في ارشيف إدارة التطبيق
        </p>
    </div>
</div>
@section Scripts{
    <script>

        $(function () {
            $.ajax({
                url: "@Url.Action("Getlb_Requests","Tumors")",
                type: "GET",
                Data: {},
                success: function (response) {
                    $.each(response, function (k, v) {
                        $("#myTbody").append(`<tr id="row`+v.Id+`">
                                           <td>` + v.medicalNumber + `</td>
                                           <td>` + v.nationalId + `</td>
                                           <td>` + v.dateTime + `</td>
                                           <td scope="col"><button class="btn btn-sm btn-success" onclick="Delete(`+v.Id+`)"> تـــم </button></td>
                                    </tr>`);
                    });
                }
            });

            $("#medicalNumberSearch").on("keyup", function() {
                var value = $(this).val();
                $("#myTbody tr").filter(function() {
                  $(this).toggle($(this).text().indexOf(value) > -1)
                });
            });

        });

        function Delete(Id) {
            alertify.confirm(" هل تم تنفيذ الطلب ؟ ", function (e) {
                if (e) {
                    $.ajax({
                        url: "/Labs/DeleteRequest?id=" + Id,
                        type: "GET",
                        success: function (respose) {
                            $("#row" + Id).remove();
                            $.notify("تم الحذف بنجاح", "success");
                        }
                    });
                };
            });
        };



    </script>
}
<div class="pb-4">
    @Html.TextBox("medicalNumberSearch", "", new { @class = "form-control col-4 m-auto text-center", placeholder = "بحث بالرقم الطبي", type = "number" })

</div>
<table id="myTable" class="table .thead-light text-center col-8 m-auto">
    <thead>
        <tr>
            <th scope="col">الرقم الطبي</th>
            <th scope="col">الرقم القومي</th>
            <th scope="col">الوقت / التاريخ</th>
            <th></th>
        </tr>
    </thead>
    <tbody id="myTbody" class="text-center">
    </tbody>
</table>

Views/Tumors/patientProfile.cshtml
@{
    if (@Session["uId"] == null)
    {
        Response.Redirect("/Login/login");
    }
    ViewBag.Title = "الأورام";
    Layout = "~/Views/Shared/_Tur.cshtml";
}

@section Styles{

    <style>
        .Pcard {
            box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
            transition: 0.3s;
        }

            .Pcard:hover {
                box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
            }

        .Pcontainer {
            padding: 2px 16px;
        }
    </style>

}
@section Scripts{
    <script>
        var patientId;
        var url = window.location.pathname;
        var id = url.substring(url.lastIndexOf('/') + 1);
        $(function () {
            $.ajax({
                type: "GET",
                url: "@Url.Action("getPatientById","Tumors")",
                data: { id },
                success: function (res) {
                    patientId = res.Id;
                    $("#userName").append(res.userName);
                    $("#medicalNumber").append(res.medicalNumber);
                }
            });
            $.ajax({
                type: "GET",
                url: "@Url.Action("GetPatientResult","Tumors")",
                data: { id },
                success: function (response) {
                    $.each(response, function (k, v) {
                        $("#myTbody").append(`<tr id="rowId-` + v.Id + `">
                                    <td>
                                    <a class = "icons ion-trash-a text-light" onclick="Delete(fileId = ` + v.Id + ` ,FileName ='`+ v.Name +`')"></a>
                                    </td>
                                    <td>` + v.testName + `</td>
                                    <td>` + v.Datetime + `</td>
                                    <td class="text center">
                                        <a class ="text-light pl-3" href="/Tumors/Reader?FileName=`+ v.Name +`" target="_blank"><i class="ion-ios-book-outline"></i> قراءة</a>
                                        <a class = "text-light" href="/Tumors/Downloader?FileName=`+ v.Name +`" ><i class="ion-ios-download-outline"></i> تحميل </a>
                                    </td>
                            </tr>`
                        );
                    });
                }
            });

            $("#medicalNumberSearch").on("keyup", function() {
                var value = $(this).val();
                $("#myTbody tr").filter(function() {
                  $(this).toggle($(this).text().indexOf(value) > -1)
                });
            });

        });

        function Delete(fileId, FileName) {
            alertify.confirm("هل تريد حذف هذا التقرير ؟", function (e) {
                if (e) {
                    $.ajax({
                        url: "/Tumors/Deleter",
                        data: {
                            fileId: fileId,
                            FileName: FileName
                        },
                        contentType:"application/json",
                        success: function (res) {
                            if (res == "تم الحذف بنجاح") {
                                $("#rowId-" + fileId).remove();
                                $.notify("تم الحذف", { position:"top center", className: "success" } );
                            } else {
                                 $.notify("هذا التقرير غير متاح", { position:"top center", className: "warn" });
                            }
                        }
                    });
                }
            });
        }

    </script>
}
<div dir="rtl" class="jumbotron p-0 pr-4 pt-1 pb-1">
    <h3>
        <strong id="userName" style="font-size:40px;"></strong>
        <br />
    </h3>
    <p class="lead">
        <span id="medicalNumber">رقم طبي : </span>
    </p>
    <hr class="my-4">

    <div class="col-md-6">
        <h3>
            <strong style="color:#c0392b">@ViewBag.error</strong>
            <strong style="color:#27ae60">@ViewBag.success</strong>
        </h3>
    </div>
    <div class="col-md-6">
        @using (Html.BeginForm("uploadFile", "Tumors", new { Id = @ViewBag.patientId }, FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="form-group">
                <label>أدخل إسم التقرير</label>
                <input type="text" class="form-control" name="testName" />
            </div>
            <div class="form-group">
                <label>أختر تقرير من جهازك</label>
                <input id="File" type="file" class="form-control-file" name="upFile" accept="application/pdf">
            </div>
            <input class="btn btn-outline-primary" type="submit" name="submit" value="إرسال" />
        }
    </div>
</div>
<hr class="my-4">

<div class="p-4">
    <h4 class="text-center">قائمة التقارير</h4>

</div>
<table id="fileTable" class="table table-primary table-striped text-center" style="padding-bottom: 100px">
    <thead>
        <tr>
            <th scope="col">  </th>
            <th scope="col">إسم الملف</th>
            <th scope="col">التاريخ</th>
            <th scope="col">
                @Html.TextBox("medicalNumberSearch", "", new { @class = "form-control w-50 m-auto text-center", placeholder = "بحث", type = "text" })
            </th>
        </tr>
    </thead>
    <tbody id="myTbody">
    </tbody>
</table>