Models/Labs.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ImcLabApp.Models
{
    public class Labs
    {
        public int Id { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "من فضلك ادخل اسم التقرير")]
        public string testName { get; set; }

        [Required]
        public string Name { get; set; }
        [Required]
        public string urlName { get; set; }
        [Required]
        public string Datetime { get; set; }

        [Required]
        [ForeignKey("Patients")]
        public int patients_Id { get; set; }
        public virtual Patients Patients { get; set; }


    }
}

Controllers/Api/PatientsController.cs
using ImcLabApp.Models;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Http;
using System.Web.Http.Cors;

namespace IMCLab.Controllers.api
{
    [EnableCors(origins: "*", headers: "*", methods: "*")]
    public class PatientsController : ApiController
    {

        private AppDbContext db;
        public PatientsController()
        {
            db = new AppDbContext();
        }
        //// GET : /Api/Patients
        //public IEnumerable<Patients> GetPatients()
        //{
        //    return db.Patients.ToList();
        //}
        ////GET: Api/Patients?id = 1
        //public Patients GetPatientsbyId(int id)
        //{
        //    var patients = db.Patients.Where(e => e.Id == id).FirstOrDefault();

        //    if (patients == null)
        //        throw new HttpResponseException(HttpStatusCode.Forbidden);

        //    return patients;
        //}

        //GET: Api/Patients?medicalNumber=medicalNumber&NationalId=NationalId
        public Patients GetPatientsbyMedicalNumber(string medicalNumber, string NationalId)
        {
            var patients = db.Patients.Where(e => e.medicalNumber == medicalNumber && e.NationalID == NationalId ).FirstOrDefault();
             
            if (patients == null)
                throw new HttpResponseException(HttpStatusCode.Forbidden);
            
            return patients;
        }

        ////POST: Api/CreatePatients
        //[HttpPost]
        //public Patients CreatePatients(Patients p)
        //{
        //    if (!ModelState.IsValid)
        //        throw new HttpResponseException(HttpStatusCode.BadRequest);

        //    db.Patients.Add(p);
        //    db.SaveChanges();

        //    return p;

        //}
        ////Put: Api/UpdatePatients/1
        //[HttpPut]
        //public void UpdatePatients(int id, Patients p)
        //{
        //    if (!ModelState.IsValid)
        //        throw new HttpResponseException(HttpStatusCode.BadRequest);

        //    var PatientsInDb = db.Patients.SingleOrDefault(e => e.Id == id);

        //    if (PatientsInDb == null)
        //        throw new HttpResponseException(HttpStatusCode.Forbidden);

        //    PatientsInDb.Id = p.Id;
        //    PatientsInDb.userName = p.userName;
        //    PatientsInDb.phoneNumber = p.phoneNumber;

        //    db.SaveChanges();

        //}

        ////Put: Api/DeletePatients/1
        //[HttpDelete]
        //public void DeletePatients(int id)
        //{
        //    var PatientsInDb = db.Patients.SingleOrDefault(e => e.Id == id);

        //    if (PatientsInDb == null)
        //        throw new HttpResponseException(HttpStatusCode.BadRequest);

        //    db.Patients.Remove(PatientsInDb);
        //    db.SaveChanges();
        //}

    }
}

Controllers/Api/RequestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using ImcLabApp.Models;
namespace ImcLabApp.Controllers.Api
{
    public class RequestsController : ApiController
    {
        AppDbContext db = new AppDbContext();

        [HttpGet]
        public IEnumerable<Requests>  Requests()
        {
            var requests = db.Requests.ToList();
            return requests;
        }
        
        [HttpPost]
        public Requests Requests(Requests requests)
        {
            if (requests == null)
                throw new HttpResponseException(HttpStatusCode.BadRequest);

            db.Requests.Add(requests);
            db.SaveChanges();
            return(requests);
        }
    }
}

Controllers/LabsController.cs
using ImcLabApp.Models;
using ImcLabApp.Models.BackUpSystemModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ImcLabApp.Controllers
{
    public class LabsController : Controller
    {
        AppDbContext db = new AppDbContext();

        // GET: UserHome
        public ActionResult Index()
        {
            return View();
        }

        //--------------------------------------//
        //CRUD OPERATIONS USING ASP.NET MVC AND DATATABLE OF PATIENTS.
        //-------------------------------------//

        // GET ALL PATIENTS.
        public JsonResult GetPatients()
        {
            db.Configuration.ProxyCreationEnabled = false;
            return Json(new { data = db.Patients.ToList() }, JsonRequestBehavior.AllowGet);
        }


        [HttpGet]
        public ActionResult AddOrEdit(int id = 0)
        {
            if (id == 0)
            {
                return View(new Patients());
            }
            else
            {
                return View(db.Patients.Where(p => p.Id.Equals(id)).FirstOrDefault<Patients>());
            }
        }
        [HttpPost]
        public ActionResult AddOrEdit(int id, Patients p)
        {

            if (p.Id == 0)
            {
                var patientInDB = db.Patients.Where(m => m.medicalNumber == p.medicalNumber).FirstOrDefault();
                if (patientInDB == null)
                {
                    db.Patients.Add(p);
                    db.SaveChanges();
                    return Json(new { success = true, message = "تم الإضافة" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = true, message = "هذ المريض موجود بالفعل" }, JsonRequestBehavior.AllowGet);
                }

            }
            else
            {
                var patientInDB = db.Patients.Where(m => m.medicalNumber == p.medicalNumber).FirstOrDefault();
                if (patientInDB == null)
                {
                    db.Entry(p).State = EntityState.Modified;
                    db.SaveChanges();
                    return Json(new { success = true, message = "تم التعديل" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = true, message = "هذ المريض موجود بالفعل" }, JsonRequestBehavior.AllowGet);
                }

            }

        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            var patient = db.Patients.Where(p => p.Id.Equals(id)).FirstOrDefault();
            db.Patients.Remove(patient);
            db.SaveChanges();
            return Json(new { success = true, message = "تم المسح" }, JsonRequestBehavior.AllowGet);
        }
        //-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
        //----------------------------------------Patient Profile-------------------------------------------
        //-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

        // GET: patientsProfile
        public ActionResult patientProfile(int? id)
        {
            var patients = db.Patients.Where(e => e.Id == id).FirstOrDefault();

            ViewBag.error = TempData["error"];
            ViewBag.success = TempData["success"];
            ViewBag.patientId = patients.Id;
            return View();
        }

        public JsonResult getPatientById(int id)
        {
            db.Configuration.ProxyCreationEnabled = false;
            var patient = db.Patients.Where(p => p.Id.Equals(id)).FirstOrDefault<Patients>();
            return Json(patient, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetPatientResult(int? id)
        {
            db.Configuration.ProxyCreationEnabled = false;
            var results = db.Labs.Where(l => l.patients_Id == id).ToList();
            return Json(results, JsonRequestBehavior.AllowGet);
        }

        //-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
        //Complete Base File Controllers.
        //-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
        public ActionResult uploadFile(HttpPostedFileBase upFile, int id, Labs lab)
        {
            if (upFile != null && lab.testName != null)
            {
                if (upFile.ContentType == "application/pdf")
                {
                    Labs labs = new Labs();
                    labs.patients_Id = id;

                    var info = TimeZoneInfo.FindSystemTimeZoneById("Egypt Standard Time");
                    DateTimeOffset localServerTime = DateTimeOffset.Now;
                    DateTimeOffset localTime = TimeZoneInfo.ConvertTime(localServerTime, info);

                    var dateTime = localTime.ToString("dd/MM/yyyy hh:mm tt");

                    string UniquefileName = Guid.NewGuid() + Path.GetFileName(upFile.FileName);
                    string filePath = Server.MapPath("~/Uploaded/");
                    string actualPath = Path.Combine(filePath + UniquefileName);
                    upFile.SaveAs(actualPath);
                    labs.Name = UniquefileName;
                    labs.urlName = actualPath;
                    labs.testName = lab.testName;
                    labs.Datetime = dateTime;

                    db.Labs.Add(labs);
                    db.SaveChanges();
                    ViewData["uploadSuccessMessage"] = "تم الرفع بنجاح";
                    TempData["success"] = ViewData["uploadSuccessMessage"];
                    return RedirectToAction("patientProfile/" + id);
                }
                else
                {
                    ViewData["errorTypeMessage"] = "هذا الملف ليس pdf";
                    TempData["error"] = ViewData["errorTypeMessage"];
                    return RedirectToAction("patientProfile/" + id);
                }

            }
            else
            {
                ViewData["uploadErrorMessage"] = "من فضلك إختر الملف أو ادخل أسم التحليل";
                TempData["error"] = ViewData["uploadErrorMessage"];
                return RedirectToAction("patientProfile/" + id);

            }
        }
        public FileResult Reader(string FileName)
        {
            string filePath = Server.MapPath("~/Uploaded/");

            string actualPath = Path.Combine(filePath + FileName);

            FileStream fileStream = new FileStream(actualPath, FileMode.Open, FileAccess.Read);

            FileStreamResult fsResult = new FileStreamResult(fileStream, "application/pdf");

            return fsResult;
        }
        public ActionResult Downloader(string FileName)
        {
            string filePath = Server.MapPath("~/Uploaded/");

            string fullPath = Path.Combine(filePath + FileName);

            byte[] fileBytes = System.IO.File.ReadAllBytes(fullPath);

            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, FileName);

        }
        public JsonResult Deleter( int fileId, string FileName)
        {

            var fileInDb = db.Labs.Where(t => t.Id == fileId).FirstOrDefault();

            var fileInBackUpTests = db.tb_LabsBackUps.Where(b => b.Name == FileName).FirstOrDefault();
            string filePath = Server.MapPath("~/Uploaded/");
            string fullPath = Path.Combine(filePath + FileName);

            //----------------------------------------------------------------------------
            var info = TimeZoneInfo.FindSystemTimeZoneById("Egypt Standard Time");
            DateTimeOffset localServerTime = DateTimeOffset.Now;
            DateTimeOffset localTime = TimeZoneInfo.ConvertTime(localServerTime, info);
            //----------------------------------------------------------------------------

            if (System.IO.File.Exists(path: fullPath))
            {
                if (fileInBackUpTests != null)
                {
                    db.Labs.Remove(fileInDb);
                    db.SaveChanges();
                    return Json("تم الحذف بنجاح", JsonRequestBehavior.AllowGet);
                }
                else
                {
                    tb_labsBackUp tb_LabsBackUp = new tb_labsBackUp();

                    var TestName = fileInDb.testName;
                    var fileName = fileInDb.Name;
                    var fileUrl = fileInDb.urlName;
                    var AddedDate = fileInDb.Datetime;
                    var patientId = fileInDb.patients_Id;

                    //get patient from database.
                    var patients = db.Patients.Where(p => p.Id == patientId).FirstOrDefault();
                    var patientName = patients.userName;
                    var patientMedicalNumber = patients.medicalNumber;
                    var userName = Session["uName"].ToString();

                    //copying data from tests table to backup table.
                    tb_LabsBackUp.testName = TestName;
                    tb_LabsBackUp.Name = fileName;
                    tb_LabsBackUp.urlName = fileUrl;
                    tb_LabsBackUp.dateWasAdded = AddedDate;
                    tb_LabsBackUp.PatientName = patientName;
                    tb_LabsBackUp.PatientMedicalNumber = patientMedicalNumber;
                    tb_LabsBackUp.UserName = userName;
                    tb_LabsBackUp.Datetime = localTime.ToString("dd/MM/yyyy hh:mm tt");
                    tb_LabsBackUp.patients_Id = patientId;

                    db.tb_LabsBackUps.Add(tb_LabsBackUp);
                    db.Labs.Remove(fileInDb);
                    db.SaveChanges();
                }

            }
            else
            {
                return Json("هذا الملف غير متاح",JsonRequestBehavior.AllowGet);
            }

            return Json("تم الحذف بنجاح", JsonRequestBehavior.AllowGet);

        }

        public ActionResult Requests()
        {

Controllers/LoginController.cs
using ImcLabApp.Languages;
using ImcLabApp.Models;
using System.Linq;
using System.Web.Mvc;

namespace ImcLabApp.Controllers
{
    [HandleError]
    public class LoginController : Controller
    {
        AppDbContext db = new AppDbContext();

        // GET: Login
        public ActionResult login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult login(Users users)
        {

            var userInDb = db.Users.Where(u => u.UserName == users.UserName && u.Password == users.Password).FirstOrDefault();
            
            if (userInDb != null)
            {
                var userDept = userInDb.Departments;
                if (userDept == "إشعة")
                {
                    Session["uId"] = userInDb.Id;
                    Session["uName"] = userInDb.UserName;
                    return RedirectToAction("Index", "Radios");
                }
                else if (userDept == "أورام")
                {
                    Session["uId"] = userInDb.Id;
                    Session["uName"] = userInDb.UserName;
                    return RedirectToAction("Index", "Tumors");
                }
                else if (userDept == "معمل")
                {
                    Session["uId"] = userInDb.Id;
                    Session["uName"] = userInDb.UserName;
                    return RedirectToAction("Index", "Labs");
                }
                else if (userDept == "مدير")
                {
                    Session["uId"] = userInDb.Id;
                    Session["uName"] = userInDb.UserName;
                    return RedirectToAction("Index", "adminPanel");
                }
                else
                {
                    ViewBag.errorMessage = LoginMessages.errorMessageUserNotFound;
                    return View("login", users);
                }
            }
            else
            {
                ViewBag.errorMessage = LoginMessages.errorMessageUserNameOrPasswordWrong;
                return View("login", users);
            }
        }

        public ActionResult logout()
        {
            Session.Abandon(); // it will clear the session at the end of request
            return RedirectToAction("login");
        }

    }
}

Views/Shared/_Admin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>المركز الطبي العالمي | @ViewBag.Title</title>
    <link rel="icon" type="image/png" sizes="96x96" href="~/Content/favicon/favicon-96x96.png">
    <link href="https://fonts.googleapis.com/css?family=Almarai:400,700&display=swap" rel="stylesheet">
    <link href="~/Content/jquery-ui-1.12.1/jquery-ui.min.css" rel="stylesheet" />

    @Styles.Render("~/bundles/css")
    @Styles.Render("~/bundles/alertfiyCss")
    @RenderSection("Styles", required: false)
</head>
<body dir="rtl" style="text-align:right">
    <nav dir="ltr" class="navbar navbar-expand-md navbar-dark bg-primary sticky-top">
        <div class="container-fluid">
            <div class="navbar-brand">
                <img src="~/images/IMC.png" width="60" height="57" class="d-inline-block align-top" alt="logo image">
            </div><span class="text-light font-weight-bold">@Session["uName"] أهلاً </span>

            <div dir="rtl" class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        @Html.ActionLink("الصحفة الرئيسية", "Index", "adminPanel", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            أرشيف التقارير
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown" style="text-align:right">
                            @Html.ActionLink("المعامل", "getBackUpTests", "Lab_BackUp", new { }, new { @class = "dropdown-item" })
                            @Html.ActionLink("الإشاعات", "getBackUpTests", "Radios_BackUp", new { }, new { @class = "dropdown-item" })
                            @Html.ActionLink("الأورام", "getBackUpTests", "Tumors_BackUp", new { }, new { @class = "dropdown-item" })
                        </div>
                    </li>
                    @*<li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            أرشيف الطلبات
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown" style="text-align:right">
                            @Html.ActionLink("المعامل", "lbReqestBackup", "RequstsBackUp", new { }, new { @class = "dropdown-item" })
                            @Html.ActionLink("الإشاعات", "rdReqestBackup", "RequstsBackUp", new { }, new { @class = "dropdown-item" })
                            @Html.ActionLink("الأورام", "trReqestBackup", "RequstsBackUp", new { }, new { @class = "dropdown-item" })
                        </div>
                    </li>*@
                    <li class="nav-item">
                        @Html.ActionLink("المرضى", "Patients", "adminPanel", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("الخروج", "Logout", "login", null, new { @class = "nav-link " })
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class=" container-fluid body-content" style="height:79.9vh">
        @RenderBody()
    </div>
    @{
        Html.RenderPartial("_Footer");
    }
    @Scripts.Render("~/bundles/jQuery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Content/jquery-ui-1.12.1/jquery-ui.min.js"></script>
    @Scripts.Render("~/bundles/notify")
    @Scripts.Render("~/bundles/alertfiyJs")
    <script type="text/javascript">
        alertify.defaults.glossary.title = 'تأكيد ';
        alertify.defaults.glossary.ok = 'نعم';
        alertify.defaults.glossary.cancel = 'لا';
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Footer.cshtml
    <footer>
        <div class="container">
            <p> جميع الحقوق محفوظة 2019 &copy; المركز الطبي العالمي - فرع نظم المعلومات</p>
        </div>
    </footer>

Views/Shared/_Lab.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>المركز الطبي العالمي | @ViewBag.Title</title>
    <link rel="icon" type="image/png" sizes="96x96" href="~/Content/favicon/favicon-96x96.png">
    <link href="https://fonts.googleapis.com/css?family=Almarai:400,700&display=swap" rel="stylesheet">
    <link href="~/DataTables/datatables.min.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui-1.12.1/jquery-ui.min.css" rel="stylesheet" />

    @Styles.Render("~/bundles/css")
    @Styles.Render("~/bundles/alertfiyCss")
    @RenderSection("Styles", required: false)
</head>
<body dir="rtl" style="text-align:right">
    <nav dir="ltr" class="navbar navbar-expand-md navbar-dark bg-primary sticky-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <img src="~/images/IMC.png" height="75" width="75" class="d-inline-block align-top" alt="logo image">
            </a>

            <div dir="rtl" class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        @Html.ActionLink("الصحفة الرئيسية", "Index", "Labs", new { }, new { @class = "nav-link" })
                    </li>
                    @*<li class="nav-item">
                        @Html.ActionLink("الطلبات", "Requests", "Labs", new { }, new { @class = "nav-link" })
                    </li>*@
                    <li class="nav-item">
                        @Html.ActionLink("الخروج", "Logout", "Login", null, new { @class = "nav-link " })
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="body-content container-fluid" style="height:100%">
        @RenderBody()
    </div>
    @{
        Html.RenderPartial("_Footer");
    }
    @Scripts.Render("~/bundles/jQuery")
    <script src="~/DataTables/datatables.min.js"></script>
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Content/jquery-ui-1.12.1/jquery-ui.min.js"></script>
    @Scripts.Render("~/bundles/notify")
    @Scripts.Render("~/bundles/alertfiyJs")
    <script type="text/javascript">
        alertify.defaults.glossary.title = 'تأكيد ';
        alertify.defaults.glossary.ok = 'نعم';
        alertify.defaults.glossary.cancel = 'لا';
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_LandingPage.cshtml
<!DOCTYPE html>

<html lang="ar">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> المركز الطبي العالمي | دخــول</title>
    <link rel="icon" type="image/png" sizes="96x96" href="~/Content/favicon/favicon-96x96.png">
    <link href="https://fonts.googleapis.com/css?family=Almarai:400,700&display=swap" rel="stylesheet">
    @Styles.Render("~/bundles/css")
    <style>
        body{
            overflow:hidden;
        }
    </style>
</head>
<body dir="rtl">
    <div>
        @RenderBody()
    </div>
    @{
        Html.RenderPartial("_Footer");
    }
    @Scripts.Render("~/bundles/jQuery");
    @Scripts.Render("~/bundles/bootstrap");
</body>
</html>

Views/Shared/_Rad.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>المركز الطبي العالمي | @ViewBag.Title</title>
    <link rel="icon" type="image/png" sizes="96x96" href="~/Content/favicon/favicon-96x96.png">
    <link href="https://fonts.googleapis.com/css?family=Almarai:400,700&display=swap" rel="stylesheet">
    <link href="~/DataTables/datatables.min.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui-1.12.1/jquery-ui.min.css" rel="stylesheet" />

    @Styles.Render("~/bundles/css")
    @Styles.Render("~/bundles/alertfiyCss")
    @RenderSection("Styles", required: false)
</head>
<body dir="rtl" style="text-align:right">
    <nav dir="ltr" class="navbar navbar-expand-md navbar-dark bg-primary sticky-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <img src="~/images/IMC.png" height="75" width="75" class="d-inline-block align-top" alt="logo image">
            </a>

            <div dir="rtl" class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        @Html.ActionLink("الصحفة الرئيسية", "Index", "Labs", new { }, new { @class = "nav-link" })
                    </li>
                    @*<li class="nav-item">
                        @Html.ActionLink("الطلبات", "Requests", "Radios", new { }, new { @class = "nav-link" })
                    </li>*@
                    <li class="nav-item">
                        @Html.ActionLink("الخروج", "Logout", "Login", null, new { @class = "nav-link " })
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="body-content container-fluid" style="height:100%">
        @RenderBody()
    </div>
    @{
        Html.RenderPartial("_Footer");
    }
    @Scripts.Render("~/bundles/jQuery")
    <script src="~/DataTables/datatables.min.js"></script>
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Content/jquery-ui-1.12.1/jquery-ui.min.js"></script>
    @Scripts.Render("~/bundles/notify")
    @Scripts.Render("~/bundles/alertfiyJs")
    <script type="text/javascript">
        alertify.defaults.glossary.title = 'تأكيد ';
        alertify.defaults.glossary.ok = 'نعم';
        alertify.defaults.glossary.cancel = 'لا';
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Tur.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>المركز الطبي العالمي | @ViewBag.Title</title>
    <link rel="icon" type="image/png" sizes="96x96" href="~/Content/favicon/favicon-96x96.png">
    <link href="https://fonts.googleapis.com/css?family=Almarai:400,700&display=swap" rel="stylesheet">
    <link href="~/DataTables/datatables.min.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui-1.12.1/jquery-ui.min.css" rel="stylesheet" />

    @Styles.Render("~/bundles/css")
    @Styles.Render("~/bundles/alertfiyCss")
    @RenderSection("Styles", required: false)
</head>
<body dir="rtl" style="text-align:right">
    <nav dir="ltr" class="navbar navbar-expand-md navbar-dark bg-primary sticky-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <img src="~/images/IMC.png" height="75" width="75" class="d-inline-block align-top" alt="logo image">
            </a>

            <div dir="rtl" class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        @Html.ActionLink("الصحفة الرئيسية", "Index", "Labs", new { }, new { @class = "nav-link" })
                    </li>
                    @*<li class="nav-item">
                        @Html.ActionLink("الطلبات", "Requests", "Tumors", new { }, new { @class = "nav-link" })
                    </li>*@
                    <li class="nav-item">
                        @Html.ActionLink("الخروج", "Logout", "Login", null, new { @class = "nav-link " })
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="body-content container-fluid" style="height:100%">
        @RenderBody()
    </div>
    @{
        Html.RenderPartial("_Footer");
    }
    @Scripts.Render("~/bundles/jQuery")
    <script src="~/DataTables/datatables.min.js"></script>
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Content/jquery-ui-1.12.1/jquery-ui.min.js"></script>
    @Scripts.Render("~/bundles/notify")
    @Scripts.Render("~/bundles/alertfiyJs")
    <script type="text/javascript">
        alertify.defaults.glossary.title = 'تأكيد ';
        alertify.defaults.glossary.ok = 'نعم';
        alertify.defaults.glossary.cancel = 'لا';
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>